---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: Run the equivalent of "apt update" as a separate step (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Upgrade packages and update dnf cache (Fedora)
    dnf:
      name: '*'
      update_cache: yes
      state: latest
    when: ansible_distribution == 'Fedora'

  tasks: 
  - name: Add RPMFusion free gpg key
    rpm_key:
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
      state: present
    when: ansible_distribution == 'Fedora' and ansible_distribution_version == '34'

  - name: Add RPMFusion nonfree gpg key
    rpm_key:
      key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
      state: present
    when: ansible_distribution == 'Fedora' and ansible_distribution_version == '34'

  - name: Install RPM Fusion Repositories
    dnf:
      name: 
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-34.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-34.noarch.rpm
      state: present
    when: ansible_distribution == 'Fedora' and ansible_distribution_version == '34'

  - name: Install basic utilities packages
    package:
      name: 
        - htop
        - neofetch
        - ncdu
      state: present

  - name: Install pdf utilities packages
    package:
      name:
        - poppler-utils
        - pdfarranger
        - pdfgrep
      state: present

  - name: Install VLC
    package:
      name: vlc
      state: present

  # Install Okular from the repository for Fedora
  - name: Install Okular
    package:
      name: okular
      state: present
    when: ansible_distribution == 'Fedora' 

  - name: Install Gnome extensions packages
    package:
      name: 
        - gnome-extensions-app
        - gnome-shell-extension-appindicator
      state: present

  - name: Install Flameshot
    package:
      name: flameshot
      state: present

  - name: Install Flatpak
    package:
      name: flatpak
      state: present

  - name: Remove unnecessary packages
    package:
      name:
        - totem # Default Gnome Video Player
      state: absent
