---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: Upgrade packages and update dnf cache (Fedora)
    dnf:
      name: '*'
      update_cache: yes
      state: latest
    when: ansible_distribution == 'Fedora'

  tasks: 
  - name: Install RPM Fusion Repositories
    dnf:
      name: 
        - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-34.noarch.rpm
        - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-34.noarch.rpm
      disable_gpg_check: yes
      state: present
    when: ansible_distribution == 'Fedora' and ansible_distribution_version == '34'

  - name: Install basic utilities packages
    package:
      name: 
        - htop
        - neofetch
        - ncdu
      state: present

  - name: Install pdf utilities packages
    package:
      name:
        - poppler-utils
        - pdfarranger
        - pdfgrep
      state: present

  - name: Install VLC
    package:
      name: vlc
      state: present

  - name: Install Okular
    package:
      name: okular
      state: present

  - name: Install Gnome extensions packages
    package:
      name: 
        - gnome-extensions-app
        - gnome-shell-extension-appindicator
      state: present

  - name: Install Flameshot
    package:
      name: flameshot
      state: present

  - name: Install Flatpak
    package:
      name: flatpak
      state: present

  - name: Remove unnecessary packages
    package:
      name:
        - totem # Default Gnome Video Player
      state: absent
