---
- hosts: localhost
  connection: local
  become: true

  tasks: 
  - name: Install basic utilities packages
    package:
      name: 
        - htop
        - neofetch
        - ncdu
      state: present

  - name: Remove unnecessary packages
    package:
      name:
        - totem # Default Gnome Video Player
      state: absent
